<?php

namespace App\System\Extensions\Plugin\Core;

use Extensions\Plugins\Shop_todyxe__911590082\App\Middleware\Testss;
use Illuminate\Contracts\Http\Kernel;
use Illuminate\Support\ServiceProvider;

abstract class PluginServiceProvider extends ServiceProvider {

    protected $pluginName;
    protected $routeNamespace = "Extensions\\Plugins\\";
    protected $eid;

    protected $middleware = [];

    protected $middlewareGroups = [];

    protected $middlewarePriority = [];

    protected $middlewareRoute = [];

    public function __construct($app)
    {
        $this->eid = explode("__", $this->pluginName)[1];

        parent::__construct($app);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
    }

    /**
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    protected function registerAllMiddlewares()
    {
        $this->addMiddleware($this->middleware);
        $this->addMiddlewareGroup($this->middlewareGroups);
        $this->addMiddlewarePriority($this->middlewarePriority);
        $this->addMiddlewareRoute($this->middlewareRoute);
    }

    /**
     * @param $middleware
     * @param bool $prepend
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    protected function addMiddleware($middleware, bool $prepend = false)
    {
        $middlewares = is_array($middleware) ? $middleware : [$middleware];

        $kernel = $this->app->make(Kernel::class);

        foreach ($middlewares as $middleware) {
            if ($prepend) {
                $kernel->prependMiddleware($middleware);
            } else {
                $kernel->pushMiddleware($middleware);
            }
        }
    }

    /**
     * @param $name
     * @param array $middleware
     */
    protected function addMiddlewareGroup($name, $middleware = [])
    {
        $middlewares = is_array($name) ? $name : [$name => $middleware];

        foreach ($middlewares as $key => $middleware) {
            $this->app['router']->middlewareGroup($key, $middleware);
        }
    }

    /**
     * @param $middleware
     */
    protected function addMiddlewarePriority($middleware)
    {
        $middlewares = is_array($middleware) ? $middleware : [$middleware];

        foreach ($middlewares as $middleware) {
            $this->app['router']->middlewarePriority[] = $middleware;
        }
    }

    /**
     * @param $name
     * @param array $middleware
     */
    protected function addMiddlewareRoute($name, $middleware = [])
    {
        $middlewares = is_array($name) ? $name : [$name => $middleware];

        foreach ($middlewares as $k => $middleware) {
            $this->app['router']->aliasMiddleware($k, $middleware);
        }
    }

    /**
     * @return mixed
     */
    protected function registerAdminNavbar()
    {
        $navAdminFile = collect(include $this->getPath("Config/NavAdmin.php"));
        $navAdminFile->put("plugin__eid", $this->eid);

        if($navAdminFile->isEmpty())
            return $this->app['plugin.navbar.admin']->getNavbarList();

        return $this->app['plugin.navbar.admin']->addNavbar($navAdminFile->toArray());
    }

    /**
     * @return mixed
     */
    public function registerUserRoutes()
    {
        $navUserFile = collect(include $this->getPath("Config/NavUser.php"));
        $navUserFile->put("plugin__eid", $this->eid);

        if($navUserFile->isEmpty())
            return $this->app['plugin.navbar.user']->getNavbarList();

        return $this->app['plugin.navbar.user']->addNavbar($navUserFile->toArray());
    }

    /**
     * @return ServiceProvider
     */
    protected function loadRoutes()
    {
        return $this->app->register($this->routeNamespace . $this->pluginName . "\\Providers\\RouteServiceProvider");
    }

    /**
     * Load all views
     */
    protected function loadViews()
    {
        parent::loadViewsFrom($this->getPath("Resources/views"), $this->eid);
    }

    /**
     * Load all php array translations
     */
    protected function loadTranslations()
    {
        parent::loadTranslationsFrom($this->getPath("Resources/lang"), $this->getPluginConfig('aliases'));
    }

    /**
     * Load all migrations
     */
    protected function loadMigrations()
    {
        parent::loadMigrationsFrom($this->getPath("DataBase/migrations"));
    }

    /**
     * Load all factories
     */
    protected function loadFactories()
    {
        parent::loadFactoriesFrom($this->getPath("DataBase/factories")); // TODO: Change the autogenerated stub
    }

    /**
     * @param $key
     * @return mixed
     */
    protected function getPluginConfig($key)
    {
        return plugin()->getConfig($this->eid, $key);
    }

    /**
     * @param $folder
     * @return string
     */
    protected function getPath($folder)
    {
        return extensions_path("Plugins/" . $this->pluginName . "/" . $folder);
    }

}